# Window
WINDOW_SIZE_X = 768
WINDOW_SIZE_Y = 768
WINDOW_SIZE_X_HALF = WINDOW_SIZE_X // 2
WINDOW_SIZE_Y_HALF = WINDOW_SIZE_Y // 2
WINDOW_TITLE = 'vital.io'
FPS = 120

# Map
ROWS, COLS = 64, 64
MAP_CELL_TILE = 64
MAP_CELL_WIDTH = 1
MAP_CELLS_ON_SCREEN_X = WINDOW_SIZE_X // MAP_CELL_TILE
MAP_CELLS_ON_SCREEN_Y = WINDOW_SIZE_Y // MAP_CELL_TILE
MAP_CELL_TILE_RADIUS = 12
MAP_SIZE_X = ROWS * MAP_CELL_TILE
MAP_SIZE_Y = COLS * MAP_CELL_TILE

# Food
FOOD_CELL_TILE = 16
FOOD_CELL_TILE_HALF = FOOD_CELL_TILE // 2
FOOD_AMOUNT = 64
FOOD_COLOR = (255, 141, 0)
FOOD_ENERGY = 1.5

# Player
PLAYER_START_POS = (MAP_SIZE_X // 2, MAP_SIZE_Y // 2)
PLAYER_START_TILE = 64
PLAYER_START_TILE_HALF = PLAYER_START_TILE // 2
PLAYER_COLOR = (200, 70, 20)
PLAYER_MOVEMENT_SPEED = 50

# Zoom
ZOOM_IN_LIMIT = 1
ZOOM_OUT_LIMIT = -8
ZOOM_STEP = 0.1

# Text
MENU_TEXT_COLOR = (180, 80, 20)
MENU_TEXT_BACKGROUND_COLOR = (0, 0, 0)
MENU_TEXT_BACKGROUND_COLOR_SELECTED = (40, 20, 10)
SCORE_TEXT_COLOR = (0, 127, 255)
