WINDOW_SIZE_X = 768
WINDOW_SIZE_Y = 768
WINDOW_SIZE_X_HALF = WINDOW_SIZE_X // 2
WINDOW_SIZE_Y_HALF = WINDOW_SIZE_Y // 2
FPS = 60

ROWS, COLS = 32, 32
MAP_CELL_TILE = 64
MAP_CELLS_ON_SCREEN_X = WINDOW_SIZE_X // MAP_CELL_TILE
MAP_CELLS_ON_SCREEN_Y = WINDOW_SIZE_Y // MAP_CELL_TILE
MAP_CELL_TILE_RADIUS = MAP_CELL_TILE // 5
MAP_SIZE_X = ROWS * MAP_CELL_TILE
MAP_SIZE_Y = COLS * MAP_CELL_TILE

FOOD_CELL_TILE = 16
FOOD_CELL_TILE_HALF = FOOD_CELL_TILE // 2
FOOD_AMOUNT = 100
FOOD_COLOR = (255, 141, 0)

PLAYER_START_POS = (MAP_SIZE_X // 2, MAP_SIZE_Y // 2)
PLAYER_START_TILE = 64
PLAYER_START_TILE_HALF = PLAYER_START_TILE // 2
PLAYER_COLOR = (200, 70, 20)
PLAYER_MOVEMENT_SPEED = 100
